### DISCUSSION TITLE
Allowing for a default set of licenses for a model distribution

### DISCUSSION THREAD

**Discussion by lehors** [lfai/model_openness_tool#72] [Ideas]
The MOF configuration file currently expects a license to be specified for each component that is provided. This is clearly not practical and is totally disconnected from the reality we are in. In fact the vast majority of model distributions contains a single license at best. I think we should focus on encouraging model producers to have 3 licenses (for code, doc, and data) per distribution and not expect them to have a license per component.

So, I would like to propose that we change the format to allow 3 licenses to be specified at the top of the configuration file: one for code, one for doc, and one for data, which will be considered to be the default ones for the related components that are provided. We can still allow this to be overridden for each component but this would be totally optional.

On the MOT side, this would translate in a change to the evaluate and submit forms so that these can be entered first and then we would allow "default" to be selected for each component included in the distribution.

**Comment by gregcube** [comment]
I like and support this idea.

**Comment by SachinVarghese** [comment]
Thanks for starting this thread. For sure, MOT could be simplified in terms of user experience and I'm in agreement with this suggestion without changing the MOF spec. I really like the idea to simplify the MOT usage but it is possible that each MOF component could have a different licence. People sticking in one license for all components at a model level today rather than acknowledging all the various components and licences that went into building the model is part of the problem we are trying to solve here.

From a workflow POV, I also feel that we should move to a pull request based flow to update the source info in Git rather than relying on UI forms. This will be easier to support long term with changing versions of MOF and license updates if any.

**Reply by lehors** [reply]
I agree we want to keep encouraging model producers to have a type-appropriate license for each type of component. I don't think we need to require a license for each component though. In fact, the MOF already provides for more flexibility than the MOT supports. It allows for a single LICENSE file to be included in the model distribution that contains multiple licenses to cover the whole distribution.

**Comment by matthew-d-white** [comment]
Just a note on the single license topic. We are building just that with the OpenMDW license.  I will be introducing it at the LF Member Summit next week: https://sched.co/1urXi. In having a single license for any of model, data & parameters it will make complying with the MOF easier and assessing the class of models much easier (a single LICENSE file in the root directory vs. many.). 

The license will need some additional review before its published, but I think this will really make adoption much easier for the MOF.

**Reply by lehors** [reply]
So, this is different from what I'm proposing. You're talking about having a single license for all types, I was merely talking about having a single license for each type, as opposed to the current expectation of having a license for each component. But we might as well plan for a single license for all types as well to cover all cases.
We'll need to figure the best way to capture that.

**Reply by gvlx** [reply]
I suppose this could just a UX issue on the tool, where we could just ask it use a certain license as the default for the form (and replace all by that one, if needed).

**Comment by gregcube** [comment]
For the YAML representation of a model; how do we feel about something like this to accept distribution-wide and component-type specific licenses?

```
framework:
  name: 'Model Openness Framework'
  version: '1.0'
  date: '2024-12-15'
release:
  name: Model-name
  version: 7B
  license:
    distribution: Apache-2.0
    code:
    document:
    data: CDLA-Permissive-2.0
  date: '2024-10-03'
  type: language
  architecture: undisclosed
  origin: ''
  producer: ''
  contact: ''
  repository: ''
  huggingface: ''
  components:
    -
      name: 'Model architecture'
      description: "Well commented code for the model's architecture"
      license: AFL-2.0  # Component-specific license. 
    -  
      name: 'Data preprocessing code'                                                                       
      description: 'Code for data cleansing, normalization, and augmentation' 
      license: unlicensed  # Component is included, but has no license. 
    -  
      name: 'Model parameters (Final)'  
      description: 'Trained model parameters, weights and biases'
      # Omitted license implies inheritance from release/license/data.   
    - 
      name: 'Data card' 
      description: 'Documentation for datasets including source, characteristics, and preprocessing details'
      # Inherited from release/license/distribution (document and code are empty)
```

It adds the `license` key under `release` --
`distribution` would be considered the global/distribution-wide license.

If a component is not included under `release/components`, then it's, well, not included. We no longer would need the `Component not included` marker. This would translate to an on/off checkbox on the UI.

Where do we land on including component and license paths?

Component location path: Mandatory, optional, remove altogether?
License path: Mandatory, optional, remove altogether?

If license path is mandatory or optional, we'll need to further refine the YAML; maybe like this?:

```
release:
  license:
    distribution:
      path: /path/to/license
      name: Apache-2.0
    code:
      path: /path/to/license
      name: MIT
```

Let me know your thoughts.
